import { StyleSheet } from 'react-native';  

export const styles = StyleSheet.create({
    screen: {
        backgroundColor: '#d1ccc0',
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'flex-start',
        resizeMode: 'contain',
    },
    accentspace: {
        backgroundColor: '#cc8e35',
        height: 150,
        elevation: 50,
    },
    searchbar: {
        backgroundColor: '#84817a',
        color: '#f5f6fa',
        fontSize: 15,
        width: 350,
        height: 60,
        padding: 12,
        paddingLeft: 30,
        margin: 32,
        elevation: 10,
        borderRadius: 30,
    },
    searchbox: {
        height: 480,
    },
    listitem: {
        backgroundColor: '#f7f1e3',
        height: 110,
        width: 350,
        padding: 30,
        marginVertical: 8,
        marginHorizontal: 32,
        elevation: 10,
        borderRadius: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    listitemtitle: {
        color: '#3d3d3d',
        fontSize: 20,
    },
    listitemdetail: {
        color: '#84817a',
        fontSize: 10,
    },
    headertitle : {
        marginTop: 20,
        marginHorizontal: 32,
        color: '#84817a',
        fontSize: 30,
    },
    locationtime : {
        marginVertical: 5,
        marginHorizontal: 32,
        color: '#84817a',
        fontSize: 20,
    },
    details: {
        flexDirection: 'column',
        flex: 1,
        paddingTop: 50,
        justifyContent: 'flex-start',
        resizeMode: 'contain',
    },
    detailbubble: {
        backgroundColor: '#f7f1e3',
        width: 350,
        padding: 20,
        marginHorizontal: 32,
        marginVertical: 7,
        elevation: 10,
        borderRadius: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    detailbubblecenter: {
        backgroundColor: '#84817a',
        width: 350,
        padding: 20,
        marginHorizontal: 32,
        marginVertical: 7,
        elevation: 10,
        borderRadius: 15,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    detailtext: {
        color: '#84817a',
        fontSize: 20,
    },
    detailtextcenter: {
        color: '#f7f1e3',
        fontSize: 20,
    },
    centertext: { 
        paddingTop: 250,
        flexDirection: 'row',
        justifyContent: "center"
    },
    weather: {
        flexDirection: 'column',
        justifyContent: 'flex-start',
        resizeMode: 'contain',
    },
    weathericon: {
        margin: 10,
    },
    subbutton: {
        backgroundColor: '#cc8e35',
        width: 350,
        padding: 20,
        marginHorizontal: 32,
        marginVertical: 7,
        elevation: 10,
        borderRadius: 15,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    sublist: {
        marginTop: 50,
    },
    weatherpredictionbox: {
        width: 350,
        marginHorizontal: 32,
        marginVertical: 7,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    weatherpredictionrow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    weatherpredictioncell: {
        backgroundColor: '#f7f1e3',
        width: 110,
        height: 120,
        marginHorizontal: 5,
        marginVertical: 5,
        elevation: 10,
        borderRadius: 15,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    weatherpredictiontext: {
        color: '#84817a',
        fontSize: 15,
    },
    settingslistitem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    locationbubble: {
        backgroundColor: '#f7f1e3',
        width: 220,
        padding: 20,
        marginLeft: 32,
        marginVertical: 7,
        borderRadius: 15,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    unsubbutton: {
        backgroundColor: '#b33939',
        width: 120,
        padding: 20,
        marginLeft: 10,
        marginRight: 32,
        marginVertical: 7,
        elevation: 10,
        borderRadius: 15,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    unsubtext: {
        color: '#f7f1e3',
        fontSize: 20,
    }
});

export const TabNavStyles = {
    inactiveBackgroundColor: '#f5f6fa',
    inactiveTintColor: '#a4b0be',
    activeBackgroundColor: '#f5f6fa',
    activeTintColor: '#2f3542',
}